GP_LPV_LQR_params:
  GP_type: "GRAD_SGP" # GRAD_SGP, RLS_SGP,
  frequency: 60.0
  num_of_inducing: 20
  forgetting_factor: 20
  confidence_level: 0.9
  retrain_iter: 5
  batch_size: 5
  lat_gains:
    k1:
    - 0.00266
    - -0.0168
    - 0.0368
    - 0.0357
    k1_r:
    - -0.0008
    - 0.0442
    - -1.2247
    k2:
    - 0.0424
    - -0.268
    - 0.588
    - 0.57
    k2_r:
    - -0.0002
    - 0.0191
    - -0.9531
    k3:
    - 0.00952
    - -0.109
    - 0.469
    - 0.0322
  long_gains:
    k1:
    - 0.0001
    - -0.0014
    - 0.0908
    k2:
    - -0.0025
    - 0.0298
    - 0.0095

vehicle_params:
  m: 1
  C_f: 41.7372
  C_r: 29.4662
  l_f: 0.163
  l_r: 0.168
  C_m1: 52.4282
  C_m2: 5.2465
  C_m3: 1.7