/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c10 CASADI_PREFIX(c10)
#define casadi_c11 CASADI_PREFIX(c11)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_c8 CASADI_PREFIX(c8)
#define casadi_c9 CASADI_PREFIX(c9)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[2] = {0, 31};
static const casadi_int casadi_s1[1] = {2};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[2] = {0, 33};
static const casadi_int casadi_s5[1] = {3};
static const casadi_int casadi_s6[2] = {0, 29};
static const casadi_int casadi_s7[2] = {0, 27};
static const casadi_int casadi_s8[10] = {12, 1, 0, 6, 0, 1, 2, 3, 4, 9};
static const casadi_int casadi_s9[5] = {2, 1, 0, 1, 0};
static const casadi_int casadi_s10[5] = {0, 1, 2, 5, 8};
static const casadi_int casadi_s11[5] = {2, 1, 0, 1, 1};
static const casadi_int casadi_s12[26] = {12, 12, 0, 0, 1, 2, 5, 8, 8, 8, 8, 8, 11, 11, 11, 1, 2, 3, 4, 9, 3, 4, 9, 3, 4, 9};
static const casadi_int casadi_s13[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s14[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s15[3] = {0, 0, 0};
static const casadi_int casadi_s16[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s17[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s18[15] = {0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[31] = {-3.1575566204037195e-19, -3.1575566204037195e-19, -3.1575566204037195e-19, 1.9578137815313748e+00, 2.9006954090075547e+00, 3.8438073827983117e+00, 4.7878346935554790e+00, 5.8306947588018776e+00, 7.4276392571227570e+00, 8.8259597484552081e+00, 9.7916952535770569e+00, 1.0737202029436570e+01, 1.1682627353612254e+01, 1.2645737803590833e+01, 1.4031897389910025e+01, 1.5582186662379527e+01, 1.6532358689061844e+01, 1.7476565676817419e+01, 1.8420103153025508e+01, 1.9363418315155638e+01, 2.0306679778305945e+01, 2.1249931149406503e+01, 2.2193181107272292e+01, 2.3136430489846823e+01, 2.4079676681948211e+01, 2.5022907507404678e+01, 2.5966082011033240e+01, 2.6909121414425766e+01, 2.8641039465463830e+01, 2.8641039465463830e+01, 2.8641039465463830e+01};
static const casadi_real casadi_c1[28] = {1.5168667699517229e+00, 7.9892929063580831e-01, 7.2953621316789885e-01, 1.3613403342198893e-01, -4.9181799495118872e-01, -8.5725316512868344e-01, -1.1422547179021179e+00, -1.1358539512436603e+00, -7.3925559858960566e-01, -3.4185383137046355e-01, 3.3822260474219235e-01, 7.3645992462739795e-01, 1.1366985890865493e+00, 1.1322893608836835e+00, 8.9127841075322145e-01, 5.7881700293571914e-01, -3.7043141701404103e-02, -6.1165841482183891e-01, -9.4832588695175679e-01, -6.2446463427087906e-01, -2.1427274728482519e+00, -3.6091242180602356e-01, -9.3784662004315877e-01, -3.0408455811115820e-01, 2.6996542030296267e-01, 8.4593708219392538e-01, 5.7637800117765847e-01, 1.8263715168532315e+00};
static const casadi_real casadi_c2[28] = {1.6504902577932683e+00, 2.4331475211479581e-01, -5.5560325477657657e-01, -8.8862368618983023e-01, -7.8661078177619226e-01, -1.2384184595363812e-01, 7.6466014319453102e-02, -1.1490563409163945e-01, 3.5055485714667312e-01, 8.5428319433760436e-01, 8.5540178780971698e-01, 3.5546693592787704e-01, -1.1014002235391185e-01, 5.4225420252474121e-02, -5.9360421543474318e-02, -7.2049878276941959e-01, -8.9423324190197540e-01, -6.5747390040005493e-01, -5.6119040751279270e-02, 5.2595229746422900e-01, 2.0185998412225890e+00, -1.4663059367630948e-01, -3.0091808832079570e-01, -8.5787679673409545e-01, -8.5461945690309926e-01, -4.0895728041396195e-01, 2.4315189864354703e-01, 1.8267147476957568e+00};
static const casadi_real casadi_c3[33] = {-3.1575566204037195e-19, -3.1575566204037195e-19, -3.1575566204037195e-19, -3.1575566204037195e-19, 1.9578137815313748e+00, 2.9006954090075547e+00, 3.8438073827983117e+00, 4.7878346935554790e+00, 5.8306947588018776e+00, 7.4276392571227570e+00, 8.8259597484552081e+00, 9.7916952535770569e+00, 1.0737202029436570e+01, 1.1682627353612254e+01, 1.2645737803590833e+01, 1.4031897389910025e+01, 1.5582186662379527e+01, 1.6532358689061844e+01, 1.7476565676817419e+01, 1.8420103153025508e+01, 1.9363418315155638e+01, 2.0306679778305945e+01, 2.1249931149406503e+01, 2.2193181107272292e+01, 2.3136430489846823e+01, 2.4079676681948211e+01, 2.5022907507404678e+01, 2.5966082011033240e+01, 2.6909121414425766e+01, 2.8641039465463830e+01, 2.8641039465463830e+01, 2.8641039465463830e+01, 2.8641039465463830e+01};
static const casadi_real casadi_c4[29] = {4.4415373358260633e-17, 1.0771175243303106e+00, 1.3123781857980437e+00, 6.0050088825905157e-01, -2.3777365002000336e-01, -1.0060300097351524e+00, -1.1539727947030944e+00, -1.0510463519458595e+00, -1.2027601097756726e+00, -8.1603234148686710e-01, -2.5646325220951677e-03, 8.1121973406683412e-01, 1.2016048222679312e+00, 1.0584389724552536e+00, 1.1286901894141566e+00, 1.0605312022180697e+00, 3.7895940984750581e-01, -4.6491646597237662e-01, -1.0851585182666628e+00, -1.1380942624826680e+00, -6.4198751521848618e-01, 1.2620572637868226e+00, 1.1237481746569977e+00, 8.3990955505742293e-01, 3.0745427434368314e-02, -7.7528741276806601e-01, -1.2685078813503041e+00, -1.0517008867384683e+00, 2.8725284721066655e-03};
static const casadi_real casadi_c5[29] = {-1.8844153968447780e-17, 9.8991422231948800e-01, 1.7623977308091385e+00, 2.6971299582069692e+00, 2.8255506786811080e+00, 2.3452085435397314e+00, 1.3211248043551671e+00, -2.1639766079082082e-01, -1.7161036817469812e+00, -2.5316412845192224e+00, -2.8571622064441633e+00, -2.5353949713405939e+00, -1.7265912723924213e+00, -2.4905008428072856e-01, 1.2178764085216540e+00, 2.2412625672972686e+00, 2.7888073398631219e+00, 2.7538502255649497e+00, 2.1768291905378145e+00, 1.2822961423415080e+00, 6.9326721332401875e-01, -1.3278609836528248e+00, -1.6682910880676260e+00, -2.5529075347379773e+00, -2.8397253122141564e+00, -2.5851079000717205e+00, -1.5648705695406695e+00, -1.0509416926006758e+00, 3.4335733792849833e-03};
static const casadi_real casadi_c6[29] = {-3.1575566204037195e-19, -3.1575566204037195e-19, 1.9578137815313748e+00, 2.9006954090075547e+00, 3.8438073827983117e+00, 4.7878346935554790e+00, 5.8306947588018776e+00, 7.4276392571227570e+00, 8.8259597484552081e+00, 9.7916952535770569e+00, 1.0737202029436570e+01, 1.1682627353612254e+01, 1.2645737803590833e+01, 1.4031897389910025e+01, 1.5582186662379527e+01, 1.6532358689061844e+01, 1.7476565676817419e+01, 1.8420103153025508e+01, 1.9363418315155638e+01, 2.0306679778305945e+01, 2.1249931149406503e+01, 2.2193181107272292e+01, 2.3136430489846823e+01, 2.4079676681948211e+01, 2.5022907507404678e+01, 2.5966082011033240e+01, 2.6909121414425766e+01, 2.8641039465463830e+01, 2.8641039465463830e+01};
static const casadi_real casadi_c7[27] = {-7.3340732003056364e-01, -4.7845821558804569e-02, -6.2927273915169746e-01, -6.6550681607331108e-01, -3.6784688915033792e-01, -2.1592625204670457e-01, 4.2739234629110001e-03, 3.3552365362655345e-01, 4.1585702783331990e-01, 7.1930286243487762e-01, 4.1732235285102592e-01, 3.4073449052275817e-01, -3.0031023286301028e-03, -1.9277318966081602e-01, -3.2988267441319519e-01, -6.5248253287843050e-01, -6.0907276111027686e-01, -3.5690834670430915e-01, 3.4334381065526443e-01, -1.6096069642413249e+00, 1.8890174121410954e+00, -6.1164648990628723e-01, 6.7190011437556696e-01, 6.0861785064247531e-01, 6.1071722538680606e-01, -2.0154270533895069e-01, 1.4434788238697100e+00};
static const casadi_real casadi_c8[27] = {-1.4374967823321780e+00, -5.5084584504149270e-01, -3.5315117844466015e-01, 1.0811380511118529e-01, 6.6714293303896322e-01, 1.5175961359988471e-01, -1.2778278320759978e-01, 3.9378127416307207e-01, 5.2712138299104883e-01, 1.1831133144249995e-03, -5.2389361378712218e-01, -3.9638436713349634e-01, 1.1194844556168290e-01, -9.0851909473246270e-02, -6.9800008993672380e-01, -1.8406565342829151e-01, 2.5095689688881917e-01, 6.3750907499915099e-01, 6.1708706948357339e-01, 1.5824505616184352e+00, -2.2955008660575738e+00, -1.6357048138953753e-01, -5.9047494692971403e-01, 3.4534887924390079e-03, 4.7254680376413416e-01, 4.8756601939773392e-01, 1.8286810373078162e+00};
static const casadi_real casadi_c9[27] = {-3.1575566204037195e-19, 1.9578137815313748e+00, 2.9006954090075547e+00, 3.8438073827983117e+00, 4.7878346935554790e+00, 5.8306947588018776e+00, 7.4276392571227570e+00, 8.8259597484552081e+00, 9.7916952535770569e+00, 1.0737202029436570e+01, 1.1682627353612254e+01, 1.2645737803590833e+01, 1.4031897389910025e+01, 1.5582186662379527e+01, 1.6532358689061844e+01, 1.7476565676817419e+01, 1.8420103153025508e+01, 1.9363418315155638e+01, 2.0306679778305945e+01, 2.1249931149406503e+01, 2.2193181107272292e+01, 2.3136430489846823e+01, 2.4079676681948211e+01, 2.5022907507404678e+01, 2.5966082011033240e+01, 2.6909121414425766e+01, 2.8641039465463830e+01};
static const casadi_real casadi_c10[26] = {3.5016685700083405e-01, -6.1664889912979193e-01, -3.8419697690799004e-02, 3.1530859704072733e-01, 1.4567691502094168e-01, 1.3788843365636494e-01, 2.3689113634314019e-01, 8.3183618890174948e-02, 3.2093459544561176e-01, -3.1941233417578324e-01, -7.9521369880236670e-02, -2.4797836861205078e-01, -1.2240946944688294e-01, -1.4429964354046462e-01, -3.4166222305987243e-01, 4.6007469615949814e-02, 2.6731724934490314e-01, 7.4237333413459883e-01, -2.0704457313620894e+00, 3.7091169177451766e+00, -2.6511163942901286e+00, 1.3607758133879524e+00, -6.7090962281122213e-02, 2.2258603643907637e-03, -8.6132130619749547e-01, 9.4982642407513418e-01};
static const casadi_real casadi_c11[26] = {4.5287807535870922e-01, 2.0967071670067827e-01, 4.8908824866450457e-01, 5.9217474066444398e-01, -4.9420179812648957e-01, -1.7504828571150199e-01, 3.7299321622160925e-01, 1.3807104338692916e-01, -5.5625013284385960e-01, -5.5538678061047442e-01, 1.3239317116376614e-01, 3.6672026634754684e-01, -1.3081452515754199e-01, -6.3898763951558957e-01, 5.4430272511547406e-01, 4.6105487199659489e-01, 4.0978052047572955e-01, -2.1650418588470832e-02, 1.0234424478053010e+00, -4.1112659431762086e+00, 2.2601980176749064e+00, -4.5259071185764133e-01, 6.2967453956429709e-01, 4.9735580549199404e-01, 1.5926392449317706e-02, 7.7435246841284100e-01};

/* jac_traj:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* jac_traj:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c2,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* traj:(x)->(f) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c3,casadi_s4,casadi_s5,casadi_s2,casadi_c4,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* traj:(x)->(f) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c3,casadi_s4,casadi_s5,casadi_s2,casadi_c5,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* jac_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz])->(jac_jac_f_x_x,jac_jac_f_x_out_f[1x1,0nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = zeros(2x1,1nz) */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c6,casadi_s6,casadi_s2,casadi_s2,casadi_c7,1,(&w1),casadi_s3, iw, w);
  /* #3: @1 = ones(2x1,1nz) */
  w1 = 1.;
  /* #4: {@3, NULL} = vertsplit(@1) */
  w3 = w1;
  /* #5: @2 = (@2*@3) */
  w2 *= w3;
  /* #6: (@0[0] = @2) */
  for (rr=(&w0)+0, ss=(&w2); rr!=(&w0)+1; rr+=1) *rr = *ss++;
  /* #7: @0 = @0' */
  /* #8: {@2, NULL} = horzsplit(@0) */
  w2 = w0;
  /* #9: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* jac_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz])->(jac_jac_f_x_x,jac_jac_f_x_out_f[1x1,0nz]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = zeros(2x1,1nz) */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c6,casadi_s6,casadi_s2,casadi_s2,casadi_c8,1,(&w1),casadi_s3, iw, w);
  /* #3: @1 = ones(2x1,1nz) */
  w1 = 1.;
  /* #4: {@3, NULL} = vertsplit(@1) */
  w3 = w1;
  /* #5: @2 = (@2*@3) */
  w2 *= w3;
  /* #6: (@0[0] = @2) */
  for (rr=(&w0)+0, ss=(&w2); rr!=(&w0)+1; rr+=1) *rr = *ss++;
  /* #7: @0 = @0' */
  /* #8: {@2, NULL} = horzsplit(@0) */
  w2 = w0;
  /* #9: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* fwd1_traj:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c2,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_traj:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz])->(fwd_jac_f_x) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c6,casadi_s6,casadi_s2,casadi_s2,casadi_c8,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz])->(fwd_jac_f_x) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c6,casadi_s6,casadi_s2,casadi_s2,casadi_c7,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_jac_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],out_jac_jac_f_x_x[1x1,0nz],out_jac_jac_f_x_out_f[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],fwd_out_jac_f_x[1x1,0nz])->(fwd_jac_jac_f_x_x,fwd_jac_jac_f_x_out_f[1x1,0nz]) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = zeros(2x1,1nz) */
  w0 = 0.;
  /* #1: @1 = ones(2x1,1nz) */
  w1 = 1.;
  /* #2: {@2, NULL} = vertsplit(@1) */
  w2 = w1;
  /* #3: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #4: @3 = BSpline(@1) */
  casadi_clear((&w3), 1);
  CASADI_PREFIX(nd_boor_eval)((&w3),1,casadi_c9,casadi_s7,casadi_s3,casadi_s2,casadi_c10,1,(&w1),casadi_s3, iw, w);
  /* #5: @1 = input[5][0] */
  w1 = arg[5] ? arg[5][0] : 0;
  /* #6: @3 = (@3*@1) */
  w3 *= w1;
  /* #7: @2 = (@2*@3) */
  w2 *= w3;
  /* #8: (@0[0] += @2) */
  for (rr=(&w0)+0, ss=(&w2); rr!=(&w0)+1; rr+=1) *rr += *ss++;
  /* #9: @0 = @0' */
  /* #10: {@2, NULL} = horzsplit(@0) */
  w2 = w0;
  /* #11: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* fwd1_jac_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz],out_jac_jac_f_x_x[1x1,0nz],out_jac_jac_f_x_out_f[1x1,0nz],fwd_x,fwd_out_f[1x1,0nz],fwd_out_jac_f_x[1x1,0nz])->(fwd_jac_jac_f_x_x,fwd_jac_jac_f_x_out_f[1x1,0nz]) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = zeros(2x1,1nz) */
  w0 = 0.;
  /* #1: @1 = ones(2x1,1nz) */
  w1 = 1.;
  /* #2: {@2, NULL} = vertsplit(@1) */
  w2 = w1;
  /* #3: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #4: @3 = BSpline(@1) */
  casadi_clear((&w3), 1);
  CASADI_PREFIX(nd_boor_eval)((&w3),1,casadi_c9,casadi_s7,casadi_s3,casadi_s2,casadi_c11,1,(&w1),casadi_s3, iw, w);
  /* #5: @1 = input[5][0] */
  w1 = arg[5] ? arg[5][0] : 0;
  /* #6: @3 = (@3*@1) */
  w3 *= w1;
  /* #7: @2 = (@2*@3) */
  w2 *= w3;
  /* #8: (@0[0] += @2) */
  for (rr=(&w0)+0, ss=(&w2); rr!=(&w0)+1; rr+=1) *rr += *ss++;
  /* #9: @0 = @0' */
  /* #10: {@2, NULL} = horzsplit(@0) */
  w2 = w0;
  /* #11: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess:(i0[9],i1[3],i2[],i3[])->(o0,o1[12],o2[12x12,11nz],o3[],o4[0x12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+5, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+4, *cr, *cs;
  casadi_real w0, w1, w3, w5, *w6=w+16, *w7=w+18, *w8=w+20, w10, w12, *w13=w+24, *w14=w+26, w15, w16, w17, *w18=w+31, w19, *w20=w+34, w21, w22, w28, w29, w30, w31, w33, w34, w36, w37, w38, w40, w42, w43, w44, w46, w48, w49, w50, w52, *w55=w+56, *w56=w+62, *w57=w+74, *w58=w+85, *w60=w+95, *w61=w+100, *w64=w+105, *w65=w+108, *w66=w+111, *w71=w+113;
  /* #0: @0 = 50 */
  w0 = 50.;
  /* #1: @1 = input[0][6] */
  w1 = arg[0] ? arg[0][6] : 0;
  /* #2: @2 = 00 */
  /* #3: @3 = jac_traj(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w3);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: @4 = 00 */
  /* #5: @5 = jac_traj(@1, @4) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w5);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #6: @5 = (-@5) */
  w5 = (- w5 );
  /* #7: @6 = horzcat(@3, @5) */
  rr=w6;
  *rr++ = w3;
  *rr++ = w5;
  /* #8: @6 = @6' */
  /* #9: @3 = traj(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w3);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #10: @5 = traj(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w5);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #11: @7 = horzcat(@3, @5) */
  rr=w7;
  *rr++ = w3;
  *rr++ = w5;
  /* #12: @7 = @7' */
  /* #13: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #14: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #15: @8 = vertcat(@3, @5) */
  rr=w8;
  *rr++ = w3;
  *rr++ = w5;
  /* #16: @7 = (@7-@8) */
  for (i=0, rr=w7, cs=w8; i<2; ++i) (*rr++) -= (*cs++);
  /* #17: @3 = dot(@6, @7) */
  w3 = casadi_dot(2, w6, w7);
  /* #18: @5 = sq(@3) */
  w5 = casadi_sq( w3 );
  /* #19: @0 = (@0*@5) */
  w0 *= w5;
  /* #20: @5 = 80 */
  w5 = 80.;
  /* #21: @9 = 00 */
  /* #22: @10 = jac_traj(@1, @9) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w10);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #23: @11 = 00 */
  /* #24: @12 = jac_traj(@1, @11) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w12);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #25: @13 = horzcat(@10, @12) */
  rr=w13;
  *rr++ = w10;
  *rr++ = w12;
  /* #26: @13 = @13' */
  /* #27: @10 = traj(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w10);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #28: @12 = traj(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w12);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #29: @14 = horzcat(@10, @12) */
  rr=w14;
  *rr++ = w10;
  *rr++ = w12;
  /* #30: @14 = @14' */
  /* #31: @14 = (@14-@8) */
  for (i=0, rr=w14, cs=w8; i<2; ++i) (*rr++) -= (*cs++);
  /* #32: @10 = dot(@13, @14) */
  w10 = casadi_dot(2, w13, w14);
  /* #33: @12 = sq(@10) */
  w12 = casadi_sq( w10 );
  /* #34: @5 = (@5*@12) */
  w5 *= w12;
  /* #35: @0 = (@0+@5) */
  w0 += w5;
  /* #36: @5 = 1.3 */
  w5 = 1.3000000000000000e+00;
  /* #37: @12 = input[1][0] */
  w12 = arg[1] ? arg[1][0] : 0;
  /* #38: @5 = (@5*@12) */
  w5 *= w12;
  /* #39: @0 = (@0-@5) */
  w0 -= w5;
  /* #40: @5 = 0.05 */
  w5 = 5.0000000000000003e-02;
  /* #41: @12 = input[1][1] */
  w12 = arg[1] ? arg[1][1] : 0;
  /* #42: @15 = sq(@12) */
  w15 = casadi_sq( w12 );
  /* #43: @5 = (@5*@15) */
  w5 *= w15;
  /* #44: @0 = (@0+@5) */
  w0 += w5;
  /* #45: @5 = 0.5 */
  w5 = 5.0000000000000000e-01;
  /* #46: @15 = input[1][2] */
  w15 = arg[1] ? arg[1][2] : 0;
  /* #47: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #48: @5 = (@5*@16) */
  w5 *= w16;
  /* #49: @0 = (@0+@5) */
  w0 += w5;
  /* #50: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #51: @0 = -1.3 */
  w0 = -1.3000000000000000e+00;
  /* #52: @5 = 0.05 */
  w5 = 5.0000000000000003e-02;
  /* #53: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #54: @12 = (@5*@12) */
  w12  = (w5*w12);
  /* #55: @16 = 0.5 */
  w16 = 5.0000000000000000e-01;
  /* #56: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #57: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #58: @17 = 50 */
  w17 = 50.;
  /* #59: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #60: @3 = (@17*@3) */
  w3  = (w17*w3);
  /* #61: @8 = (@3*@6) */
  for (i=0, rr=w8, cs=w6; i<2; ++i) (*rr++)  = (w3*(*cs++));
  /* #62: @18 = (-@8) */
  for (i=0, rr=w18, cs=w8; i<2; ++i) *rr++ = (- *cs++ );
  /* #63: @19 = 80 */
  w19 = 80.;
  /* #64: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #65: @10 = (@19*@10) */
  w10  = (w19*w10);
  /* #66: @20 = (@10*@13) */
  for (i=0, rr=w20, cs=w13; i<2; ++i) (*rr++)  = (w10*(*cs++));
  /* #67: @18 = (@18-@20) */
  for (i=0, rr=w18, cs=w20; i<2; ++i) (*rr++) -= (*cs++);
  /* #68: {@21, @22} = vertsplit(@18) */
  w21 = w18[0];
  w22 = w18[1];
  /* #69: @23 = 00 */
  /* #70: @24 = 00 */
  /* #71: @25 = 00 */
  /* #72: @26 = 00 */
  /* #73: @27 = 00 */
  /* #74: @28 = jac_traj(@1, @27) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w28);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #75: @20 = @20' */
  /* #76: {@29, @30} = horzsplit(@20) */
  w29 = w20[0];
  w30 = w20[1];
  /* #77: @31 = (@28*@30) */
  w31  = (w28*w30);
  /* #78: @32 = 00 */
  /* #79: @33 = jac_traj(@1, @32) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w33);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #80: @34 = (@33*@29) */
  w34  = (w33*w29);
  /* #81: @31 = (@31+@34) */
  w31 += w34;
  /* #82: @35 = 00 */
  /* #83: {@34, NULL} = jac_jac_traj(@1, @11, @35) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  res1[0]=(&w34);
  res1[1]=0;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #84: @20 = (@10*@14) */
  for (i=0, rr=w20, cs=w14; i<2; ++i) (*rr++)  = (w10*(*cs++));
  /* #85: @20 = @20' */
  /* #86: {@36, @37} = horzsplit(@20) */
  w36 = w20[0];
  w37 = w20[1];
  /* #87: @38 = (@34*@37) */
  w38  = (w34*w37);
  /* #88: @31 = (@31+@38) */
  w31 += w38;
  /* #89: @39 = 00 */
  /* #90: {@38, NULL} = jac_jac_traj(@1, @9, @39) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  res1[0]=(&w38);
  res1[1]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #91: @40 = (@38*@36) */
  w40  = (w38*w36);
  /* #92: @31 = (@31+@40) */
  w31 += w40;
  /* #93: @41 = 00 */
  /* #94: @40 = jac_traj(@1, @41) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w40);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #95: @8 = @8' */
  /* #96: {@42, @43} = horzsplit(@8) */
  w42 = w8[0];
  w43 = w8[1];
  /* #97: @44 = (@40*@43) */
  w44  = (w40*w43);
  /* #98: @31 = (@31+@44) */
  w31 += w44;
  /* #99: @45 = 00 */
  /* #100: @44 = jac_traj(@1, @45) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w44);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #101: @46 = (@44*@42) */
  w46  = (w44*w42);
  /* #102: @31 = (@31+@46) */
  w31 += w46;
  /* #103: @47 = 00 */
  /* #104: {@46, NULL} = jac_jac_traj(@1, @4, @47) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  res1[0]=(&w46);
  res1[1]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #105: @8 = (@3*@7) */
  for (i=0, rr=w8, cs=w7; i<2; ++i) (*rr++)  = (w3*(*cs++));
  /* #106: @8 = @8' */
  /* #107: {@48, @49} = horzsplit(@8) */
  w48 = w8[0];
  w49 = w8[1];
  /* #108: @50 = (@46*@49) */
  w50  = (w46*w49);
  /* #109: @31 = (@31-@50) */
  w31 -= w50;
  /* #110: @51 = 00 */
  /* #111: {@50, NULL} = jac_jac_traj(@1, @2, @51) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  res1[0]=(&w50);
  res1[1]=0;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #112: @52 = (@50*@48) */
  w52  = (w50*w48);
  /* #113: @31 = (@31+@52) */
  w31 += w52;
  /* #114: @53 = 00 */
  /* #115: @54 = 00 */
  /* #116: @55 = vertcat(@0, @12, @15, @21, @22, @23, @24, @25, @26, @31, @53, @54) */
  rr=w55;
  *rr++ = w0;
  *rr++ = w12;
  *rr++ = w15;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w31;
  /* #117: @56 = dense(@55) */
  casadi_densify(w55, casadi_s8, w56, 0);
  /* #118: output[1][0] = @56 */
  casadi_copy(w56, 12, res[1]);
  /* #119: @57 = zeros(12x12,11nz) */
  casadi_clear(w57, 11);
  /* #120: @23 = 00 */
  /* #121: @58 = ones(12x1,10nz) */
  casadi_fill(w58, 10, 1.);
  /* #122: {NULL, @0, @12, @15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@58) */
  w0 = w58[1];
  w12 = w58[2];
  w15 = w58[3];
  /* #123: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #124: @5 = (@5*@0) */
  w5 *= w0;
  /* #125: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #126: @16 = (@16*@12) */
  w16 *= w12;
  /* #127: @12 = project(@13) */
  casadi_sparsify(w13, (&w12), casadi_s9, 0);
  /* #128: @24 = 00 */
  /* #129: @0 = vertcat(@15, @24) */
  rr=(&w0);
  *rr++ = w15;
  /* #130: @15 = (-@0) */
  w15 = (- w0 );
  /* #131: @21 = dot(@12, @15) */
  w21 = casadi_dot(1, (&w12), (&w15));
  /* #132: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #133: @21 = (@19*@21) */
  w21  = (w19*w21);
  /* #134: @8 = (@13*@21) */
  for (i=0, rr=w8, cr=w13; i<2; ++i) (*rr++)  = ((*cr++)*w21);
  /* #135: @20 = (-@8) */
  for (i=0, rr=w20, cs=w8; i<2; ++i) *rr++ = (- *cs++ );
  /* #136: @12 = project(@6) */
  casadi_sparsify(w6, (&w12), casadi_s9, 0);
  /* #137: @15 = (-@0) */
  w15 = (- w0 );
  /* #138: @22 = dot(@12, @15) */
  w22 = casadi_dot(1, (&w12), (&w15));
  /* #139: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #140: @22 = (@17*@22) */
  w22  = (w17*w22);
  /* #141: @18 = (@6*@22) */
  for (i=0, rr=w18, cr=w6; i<2; ++i) (*rr++)  = ((*cr++)*w22);
  /* #142: @20 = (@20-@18) */
  for (i=0, rr=w20, cs=w18; i<2; ++i) (*rr++) -= (*cs++);
  /* #143: {@12, @15} = vertsplit(@20) */
  w12 = w20[0];
  w15 = w20[1];
  /* #144: @24 = 00 */
  /* #145: @25 = 00 */
  /* #146: @26 = 00 */
  /* #147: @53 = 00 */
  /* #148: @8 = @8' */
  /* #149: {@31, @52} = horzsplit(@8) */
  w31 = w8[0];
  w52 = w8[1];
  /* #150: @52 = (@28*@52) */
  w52  = (w28*w52);
  /* #151: @31 = (@33*@31) */
  w31  = (w33*w31);
  /* #152: @52 = (@52+@31) */
  w52 += w31;
  /* #153: @8 = (@14*@21) */
  for (i=0, rr=w8, cr=w14; i<2; ++i) (*rr++)  = ((*cr++)*w21);
  /* #154: @21 = (@10*@0) */
  w21  = (w10*w0);
  /* #155: @21 = (-@21) */
  w21 = (- w21 );
  /* #156: @20 = dense(@21) */
  casadi_densify((&w21), casadi_s9, w20, 0);
  /* #157: @8 = (@8+@20) */
  for (i=0, rr=w8, cs=w20; i<2; ++i) (*rr++) += (*cs++);
  /* #158: @8 = @8' */
  /* #159: {@21, @31} = horzsplit(@8) */
  w21 = w8[0];
  w31 = w8[1];
  /* #160: @31 = (@34*@31) */
  w31  = (w34*w31);
  /* #161: @52 = (@52+@31) */
  w52 += w31;
  /* #162: @21 = (@38*@21) */
  w21  = (w38*w21);
  /* #163: @52 = (@52+@21) */
  w52 += w21;
  /* #164: @18 = @18' */
  /* #165: {@21, @31} = horzsplit(@18) */
  w21 = w18[0];
  w31 = w18[1];
  /* #166: @31 = (@40*@31) */
  w31  = (w40*w31);
  /* #167: @52 = (@52+@31) */
  w52 += w31;
  /* #168: @21 = (@44*@21) */
  w21  = (w44*w21);
  /* #169: @52 = (@52+@21) */
  w52 += w21;
  /* #170: @18 = (@7*@22) */
  for (i=0, rr=w18, cr=w7; i<2; ++i) (*rr++)  = ((*cr++)*w22);
  /* #171: @0 = (@3*@0) */
  w0  = (w3*w0);
  /* #172: @0 = (-@0) */
  w0 = (- w0 );
  /* #173: @8 = dense(@0) */
  casadi_densify((&w0), casadi_s9, w8, 0);
  /* #174: @18 = (@18+@8) */
  for (i=0, rr=w18, cs=w8; i<2; ++i) (*rr++) += (*cs++);
  /* #175: @18 = @18' */
  /* #176: {@0, @22} = horzsplit(@18) */
  w0 = w18[0];
  w22 = w18[1];
  /* #177: @22 = (@46*@22) */
  w22  = (w46*w22);
  /* #178: @52 = (@52-@22) */
  w52 -= w22;
  /* #179: @0 = (@50*@0) */
  w0  = (w50*w0);
  /* #180: @52 = (@52+@0) */
  w52 += w0;
  /* #181: @54 = 00 */
  /* #182: @59 = 00 */
  /* #183: @60 = vertcat(@23, @5, @16, @12, @15, @24, @25, @26, @53, @52, @54, @59) */
  rr=w60;
  *rr++ = w5;
  *rr++ = w16;
  *rr++ = w12;
  *rr++ = w15;
  *rr++ = w52;
  /* #184: @61 = @60[:5] */
  for (rr=w61, ss=w60+0; ss!=w60+5; ss+=1) *rr++ = *ss;
  /* #185: (@57[:5] = @61) */
  for (rr=w57+0, ss=w61; rr!=w57+5; rr+=1) *rr = *ss++;
  /* #186: @61 = @60[:5] */
  for (rr=w61, ss=w60+0; ss!=w60+5; ss+=1) *rr++ = *ss;
  /* #187: (@57[0, 1, 2, 5, 8] = @61) */
  for (cii=casadi_s10, rr=w57, ss=w61; cii!=casadi_s10+5; ++cii, ++ss) rr[*cii] = *ss;
  /* #188: @23 = 00 */
  /* #189: @24 = 00 */
  /* #190: @25 = 00 */
  /* #191: @5 = project(@13) */
  casadi_sparsify(w13, (&w5), casadi_s11, 0);
  /* #192: @26 = 00 */
  /* #193: @16 = ones(12x1,1nz) */
  w16 = 1.;
  /* #194: {NULL, NULL, NULL, NULL, @12, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@16) */
  w12 = w16;
  /* #195: @16 = vertcat(@26, @12) */
  rr=(&w16);
  *rr++ = w12;
  /* #196: @12 = (-@16) */
  w12 = (- w16 );
  /* #197: @15 = dot(@5, @12) */
  w15 = casadi_dot(1, (&w5), (&w12));
  /* #198: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #199: @15 = (@19*@15) */
  w15  = (w19*w15);
  /* #200: @18 = (@13*@15) */
  for (i=0, rr=w18, cr=w13; i<2; ++i) (*rr++)  = ((*cr++)*w15);
  /* #201: @8 = (-@18) */
  for (i=0, rr=w8, cs=w18; i<2; ++i) *rr++ = (- *cs++ );
  /* #202: @5 = project(@6) */
  casadi_sparsify(w6, (&w5), casadi_s11, 0);
  /* #203: @12 = (-@16) */
  w12 = (- w16 );
  /* #204: @52 = dot(@5, @12) */
  w52 = casadi_dot(1, (&w5), (&w12));
  /* #205: @52 = (2.*@52) */
  w52 = (2.* w52 );
  /* #206: @52 = (@17*@52) */
  w52  = (w17*w52);
  /* #207: @20 = (@6*@52) */
  for (i=0, rr=w20, cr=w6; i<2; ++i) (*rr++)  = ((*cr++)*w52);
  /* #208: @8 = (@8-@20) */
  for (i=0, rr=w8, cs=w20; i<2; ++i) (*rr++) -= (*cs++);
  /* #209: {@5, @12} = vertsplit(@8) */
  w5 = w8[0];
  w12 = w8[1];
  /* #210: @26 = 00 */
  /* #211: @53 = 00 */
  /* #212: @54 = 00 */
  /* #213: @59 = 00 */
  /* #214: @18 = @18' */
  /* #215: {@0, @22} = horzsplit(@18) */
  w0 = w18[0];
  w22 = w18[1];
  /* #216: @22 = (@28*@22) */
  w22  = (w28*w22);
  /* #217: @0 = (@33*@0) */
  w0  = (w33*w0);
  /* #218: @22 = (@22+@0) */
  w22 += w0;
  /* #219: @18 = (@14*@15) */
  for (i=0, rr=w18, cr=w14; i<2; ++i) (*rr++)  = ((*cr++)*w15);
  /* #220: @15 = (@10*@16) */
  w15  = (w10*w16);
  /* #221: @15 = (-@15) */
  w15 = (- w15 );
  /* #222: @8 = dense(@15) */
  casadi_densify((&w15), casadi_s11, w8, 0);
  /* #223: @18 = (@18+@8) */
  for (i=0, rr=w18, cs=w8; i<2; ++i) (*rr++) += (*cs++);
  /* #224: @18 = @18' */
  /* #225: {@15, @0} = horzsplit(@18) */
  w15 = w18[0];
  w0 = w18[1];
  /* #226: @0 = (@34*@0) */
  w0  = (w34*w0);
  /* #227: @22 = (@22+@0) */
  w22 += w0;
  /* #228: @15 = (@38*@15) */
  w15  = (w38*w15);
  /* #229: @22 = (@22+@15) */
  w22 += w15;
  /* #230: @20 = @20' */
  /* #231: {@15, @0} = horzsplit(@20) */
  w15 = w20[0];
  w0 = w20[1];
  /* #232: @0 = (@40*@0) */
  w0  = (w40*w0);
  /* #233: @22 = (@22+@0) */
  w22 += w0;
  /* #234: @15 = (@44*@15) */
  w15  = (w44*w15);
  /* #235: @22 = (@22+@15) */
  w22 += w15;
  /* #236: @20 = (@7*@52) */
  for (i=0, rr=w20, cr=w7; i<2; ++i) (*rr++)  = ((*cr++)*w52);
  /* #237: @16 = (@3*@16) */
  w16  = (w3*w16);
  /* #238: @16 = (-@16) */
  w16 = (- w16 );
  /* #239: @18 = dense(@16) */
  casadi_densify((&w16), casadi_s11, w18, 0);
  /* #240: @20 = (@20+@18) */
  for (i=0, rr=w20, cs=w18; i<2; ++i) (*rr++) += (*cs++);
  /* #241: @20 = @20' */
  /* #242: {@16, @52} = horzsplit(@20) */
  w16 = w20[0];
  w52 = w20[1];
  /* #243: @52 = (@46*@52) */
  w52  = (w46*w52);
  /* #244: @22 = (@22-@52) */
  w22 -= w52;
  /* #245: @16 = (@50*@16) */
  w16  = (w50*w16);
  /* #246: @22 = (@22+@16) */
  w22 += w16;
  /* #247: @62 = 00 */
  /* #248: @63 = 00 */
  /* #249: @64 = vertcat(@23, @24, @25, @5, @12, @26, @53, @54, @59, @22, @62, @63) */
  rr=w64;
  *rr++ = w5;
  *rr++ = w12;
  *rr++ = w22;
  /* #250: @65 = @64[:3] */
  for (rr=w65, ss=w64+0; ss!=w64+3; ss+=1) *rr++ = *ss;
  /* #251: (@57[5:8] = @65) */
  for (rr=w57+5, ss=w65; rr!=w57+8; rr+=1) *rr = *ss++;
  /* #252: @65 = @64[:3] */
  for (rr=w65, ss=w64+0; ss!=w64+3; ss+=1) *rr++ = *ss;
  /* #253: (@57[3:12:3] = @65) */
  for (rr=w57+3, ss=w65; rr!=w57+12; rr+=3) *rr = *ss++;
  /* #254: @23 = 00 */
  /* #255: @24 = 00 */
  /* #256: @25 = 00 */
  /* #257: @26 = 00 */
  /* #258: @5 = ones(12x1,1nz) */
  w5 = 1.;
  /* #259: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @12, NULL, NULL} = vertsplit(@5) */
  w12 = w5;
  /* #260: @5 = fwd1_traj(@1, @26, @12) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=(&w12);
  res1[0]=(&w5);
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #261: @26 = 00 */
  /* #262: @22 = fwd1_traj(@1, @26, @12) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=(&w12);
  res1[0]=(&w22);
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #263: @20 = horzcat(@5, @22) */
  rr=w20;
  *rr++ = w5;
  *rr++ = w22;
  /* #264: @20 = @20' */
  /* #265: @5 = dot(@13, @20) */
  w5 = casadi_dot(2, w13, w20);
  /* #266: @26 = 00 */
  /* #267: @53 = 00 */
  /* #268: @22 = fwd1_jac_traj(@1, @9, @26, @12, @53) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w12);
  arg1[4]=0;
  res1[0]=(&w22);
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #269: @26 = 00 */
  /* #270: @54 = 00 */
  /* #271: @16 = fwd1_jac_traj(@1, @11, @26, @12, @54) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w12);
  arg1[4]=0;
  res1[0]=(&w16);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #272: @18 = horzcat(@22, @16) */
  rr=w18;
  *rr++ = w22;
  *rr++ = w16;
  /* #273: @18 = @18' */
  /* #274: @22 = dot(@18, @14) */
  w22 = casadi_dot(2, w18, w14);
  /* #275: @5 = (@5+@22) */
  w5 += w22;
  /* #276: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #277: @19 = (@19*@5) */
  w19 *= w5;
  /* #278: @13 = (@13*@19) */
  for (i=0, rr=w13; i<2; ++i) (*rr++) *= w19;
  /* #279: @18 = (@10*@18) */
  for (i=0, rr=w18, cs=w18; i<2; ++i) (*rr++)  = (w10*(*cs++));
  /* #280: @13 = (@13+@18) */
  for (i=0, rr=w13, cs=w18; i<2; ++i) (*rr++) += (*cs++);
  /* #281: @18 = (-@13) */
  for (i=0, rr=w18, cs=w13; i<2; ++i) *rr++ = (- *cs++ );
  /* #282: @26 = 00 */
  /* #283: @5 = fwd1_traj(@1, @26, @12) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=(&w12);
  res1[0]=(&w5);
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #284: @26 = 00 */
  /* #285: @22 = fwd1_traj(@1, @26, @12) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=(&w12);
  res1[0]=(&w22);
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #286: @8 = horzcat(@5, @22) */
  rr=w8;
  *rr++ = w5;
  *rr++ = w22;
  /* #287: @8 = @8' */
  /* #288: @5 = dot(@6, @8) */
  w5 = casadi_dot(2, w6, w8);
  /* #289: @26 = 00 */
  /* #290: @59 = 00 */
  /* #291: @22 = fwd1_jac_traj(@1, @2, @26, @12, @59) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w12);
  arg1[4]=0;
  res1[0]=(&w22);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #292: @26 = 00 */
  /* #293: @62 = 00 */
  /* #294: @16 = fwd1_jac_traj(@1, @4, @26, @12, @62) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w12);
  arg1[4]=0;
  res1[0]=(&w16);
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #295: @16 = (-@16) */
  w16 = (- w16 );
  /* #296: @66 = horzcat(@22, @16) */
  rr=w66;
  *rr++ = w22;
  *rr++ = w16;
  /* #297: @66 = @66' */
  /* #298: @22 = dot(@66, @7) */
  w22 = casadi_dot(2, w66, w7);
  /* #299: @5 = (@5+@22) */
  w5 += w22;
  /* #300: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #301: @17 = (@17*@5) */
  w17 *= w5;
  /* #302: @6 = (@6*@17) */
  for (i=0, rr=w6; i<2; ++i) (*rr++) *= w17;
  /* #303: @66 = (@3*@66) */
  for (i=0, rr=w66, cs=w66; i<2; ++i) (*rr++)  = (w3*(*cs++));
  /* #304: @6 = (@6+@66) */
  for (i=0, rr=w6, cs=w66; i<2; ++i) (*rr++) += (*cs++);
  /* #305: @18 = (@18-@6) */
  for (i=0, rr=w18, cs=w6; i<2; ++i) (*rr++) -= (*cs++);
  /* #306: {@5, @22} = vertsplit(@18) */
  w5 = w18[0];
  w22 = w18[1];
  /* #307: @26 = 00 */
  /* #308: @63 = 00 */
  /* #309: @67 = 00 */
  /* #310: @68 = 00 */
  /* #311: @69 = 00 */
  /* #312: @70 = 00 */
  /* #313: @16 = fwd1_jac_traj(@1, @27, @69, @12, @70) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w12);
  arg1[4]=0;
  res1[0]=(&w16);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #314: @30 = (@30*@16) */
  w30 *= w16;
  /* #315: @13 = @13' */
  /* #316: {@16, @52} = horzsplit(@13) */
  w16 = w13[0];
  w52 = w13[1];
  /* #317: @28 = (@28*@52) */
  w28 *= w52;
  /* #318: @30 = (@30+@28) */
  w30 += w28;
  /* #319: @27 = 00 */
  /* #320: @69 = 00 */
  /* #321: @28 = fwd1_jac_traj(@1, @32, @27, @12, @69) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w12);
  arg1[4]=0;
  res1[0]=(&w28);
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #322: @29 = (@29*@28) */
  w29 *= w28;
  /* #323: @33 = (@33*@16) */
  w33 *= w16;
  /* #324: @29 = (@29+@33) */
  w29 += w33;
  /* #325: @30 = (@30+@29) */
  w30 += w29;
  /* #326: @32 = 00 */
  /* #327: @27 = 00 */
  /* #328: @69 = 00 */
  /* #329: {@29, NULL} = fwd1_jac_jac_traj(@1, @11, @35, @32, @27, @12, @54, @69) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=0;
  arg1[4]=0;
  arg1[5]=(&w12);
  arg1[6]=0;
  arg1[7]=0;
  res1[0]=(&w29);
  res1[1]=0;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #330: @37 = (@37*@29) */
  w37 *= w29;
  /* #331: @14 = (@14*@19) */
  for (i=0, rr=w14; i<2; ++i) (*rr++) *= w19;
  /* #332: @20 = (@10*@20) */
  for (i=0, rr=w20, cs=w20; i<2; ++i) (*rr++)  = (w10*(*cs++));
  /* #333: @14 = (@14+@20) */
  for (i=0, rr=w14, cs=w20; i<2; ++i) (*rr++) += (*cs++);
  /* #334: @14 = @14' */
  /* #335: {@10, @19} = horzsplit(@14) */
  w10 = w14[0];
  w19 = w14[1];
  /* #336: @34 = (@34*@19) */
  w34 *= w19;
  /* #337: @37 = (@37+@34) */
  w37 += w34;
  /* #338: @30 = (@30+@37) */
  w30 += w37;
  /* #339: @11 = 00 */
  /* #340: @35 = 00 */
  /* #341: @32 = 00 */
  /* #342: {@37, NULL} = fwd1_jac_jac_traj(@1, @9, @39, @11, @35, @12, @53, @32) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=0;
  arg1[4]=0;
  arg1[5]=(&w12);
  arg1[6]=0;
  arg1[7]=0;
  res1[0]=(&w37);
  res1[1]=0;
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #343: @36 = (@36*@37) */
  w36 *= w37;
  /* #344: @38 = (@38*@10) */
  w38 *= w10;
  /* #345: @36 = (@36+@38) */
  w36 += w38;
  /* #346: @30 = (@30+@36) */
  w30 += w36;
  /* #347: @9 = 00 */
  /* #348: @39 = 00 */
  /* #349: @36 = fwd1_jac_traj(@1, @41, @9, @12, @39) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w12);
  arg1[4]=0;
  res1[0]=(&w36);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #350: @43 = (@43*@36) */
  w43 *= w36;
  /* #351: @6 = @6' */
  /* #352: {@36, @38} = horzsplit(@6) */
  w36 = w6[0];
  w38 = w6[1];
  /* #353: @40 = (@40*@38) */
  w40 *= w38;
  /* #354: @43 = (@43+@40) */
  w43 += w40;
  /* #355: @30 = (@30+@43) */
  w30 += w43;
  /* #356: @41 = 00 */
  /* #357: @9 = 00 */
  /* #358: @43 = fwd1_jac_traj(@1, @45, @41, @12, @9) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=(&w12);
  arg1[4]=0;
  res1[0]=(&w43);
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #359: @42 = (@42*@43) */
  w42 *= w43;
  /* #360: @44 = (@44*@36) */
  w44 *= w36;
  /* #361: @42 = (@42+@44) */
  w42 += w44;
  /* #362: @30 = (@30+@42) */
  w30 += w42;
  /* #363: @45 = 00 */
  /* #364: @41 = 00 */
  /* #365: @9 = 00 */
  /* #366: {@42, NULL} = fwd1_jac_jac_traj(@1, @4, @47, @45, @41, @12, @62, @9) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=0;
  arg1[4]=0;
  arg1[5]=(&w12);
  arg1[6]=0;
  arg1[7]=0;
  res1[0]=(&w42);
  res1[1]=0;
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #367: @49 = (@49*@42) */
  w49 *= w42;
  /* #368: @7 = (@7*@17) */
  for (i=0, rr=w7; i<2; ++i) (*rr++) *= w17;
  /* #369: @8 = (@3*@8) */
  for (i=0, rr=w8, cs=w8; i<2; ++i) (*rr++)  = (w3*(*cs++));
  /* #370: @7 = (@7+@8) */
  for (i=0, rr=w7, cs=w8; i<2; ++i) (*rr++) += (*cs++);
  /* #371: @7 = @7' */
  /* #372: {@3, @17} = horzsplit(@7) */
  w3 = w7[0];
  w17 = w7[1];
  /* #373: @46 = (@46*@17) */
  w46 *= w17;
  /* #374: @49 = (@49+@46) */
  w49 += w46;
  /* #375: @30 = (@30-@49) */
  w30 -= w49;
  /* #376: @4 = 00 */
  /* #377: @47 = 00 */
  /* #378: @45 = 00 */
  /* #379: {@49, NULL} = fwd1_jac_jac_traj(@1, @2, @51, @4, @47, @12, @59, @45) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  arg1[3]=0;
  arg1[4]=0;
  arg1[5]=(&w12);
  arg1[6]=0;
  arg1[7]=0;
  res1[0]=(&w49);
  res1[1]=0;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #380: @48 = (@48*@49) */
  w48 *= w49;
  /* #381: @50 = (@50*@3) */
  w50 *= w3;
  /* #382: @48 = (@48+@50) */
  w48 += w50;
  /* #383: @30 = (@30+@48) */
  w30 += w48;
  /* #384: @2 = 00 */
  /* #385: @51 = 00 */
  /* #386: @65 = vertcat(@23, @24, @25, @5, @22, @26, @63, @67, @68, @30, @2, @51) */
  rr=w65;
  *rr++ = w5;
  *rr++ = w22;
  *rr++ = w30;
  /* #387: @64 = @65[:3] */
  for (rr=w64, ss=w65+0; ss!=w65+3; ss+=1) *rr++ = *ss;
  /* #388: (@57[8:11] = @64) */
  for (rr=w57+8, ss=w64; rr!=w57+11; rr+=1) *rr = *ss++;
  /* #389: @64 = @65[:3] */
  for (rr=w64, ss=w65+0; ss!=w65+3; ss+=1) *rr++ = *ss;
  /* #390: (@57[4:13:3] = @64) */
  for (rr=w57+4, ss=w64; rr!=w57+13; rr+=3) *rr = *ss++;
  /* #391: @71 = @57' */
  casadi_trans(w57,casadi_s12, w71, casadi_s12, iw);
  /* #392: output[2][0] = @71 */
  casadi_copy(w71, 11, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s14;
    case 2: return casadi_s15;
    case 3: return casadi_s15;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s16;
    case 1: return casadi_s17;
    case 2: return casadi_s12;
    case 3: return casadi_s15;
    case 4: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 17;
  if (sz_iw) *sz_iw = 13;
  if (sz_w) *sz_w = 124;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 17*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 13*sizeof(casadi_int);
  if (sz_w) *sz_w = 124*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
