/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_bicycle_model_cost_ext_cost_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[2] = {0, 31};
static const casadi_int casadi_s1[1] = {2};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[2] = {0, 33};
static const casadi_int casadi_s5[1] = {3};
static const casadi_int casadi_s6[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s7[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[5] = {1, 1, 0, 1, 0};

static const casadi_real casadi_c0[31] = {-3.1575566204037195e-19, -3.1575566204037195e-19, -3.1575566204037195e-19, 1.9578137815313748e+00, 2.9006954090075547e+00, 3.8438073827983117e+00, 4.7878346935554790e+00, 5.8306947588018776e+00, 7.4276392571227570e+00, 8.8259597484552081e+00, 9.7916952535770569e+00, 1.0737202029436570e+01, 1.1682627353612254e+01, 1.2645737803590833e+01, 1.4031897389910025e+01, 1.5582186662379527e+01, 1.6532358689061844e+01, 1.7476565676817419e+01, 1.8420103153025508e+01, 1.9363418315155638e+01, 2.0306679778305945e+01, 2.1249931149406503e+01, 2.2193181107272292e+01, 2.3136430489846823e+01, 2.4079676681948211e+01, 2.5022907507404678e+01, 2.5966082011033240e+01, 2.6909121414425766e+01, 2.8641039465463830e+01, 2.8641039465463830e+01, 2.8641039465463830e+01};
static const casadi_real casadi_c1[28] = {1.5168667699517229e+00, 7.9892929063580831e-01, 7.2953621316789885e-01, 1.3613403342198893e-01, -4.9181799495118872e-01, -8.5725316512868344e-01, -1.1422547179021179e+00, -1.1358539512436603e+00, -7.3925559858960566e-01, -3.4185383137046355e-01, 3.3822260474219235e-01, 7.3645992462739795e-01, 1.1366985890865493e+00, 1.1322893608836835e+00, 8.9127841075322145e-01, 5.7881700293571914e-01, -3.7043141701404103e-02, -6.1165841482183891e-01, -9.4832588695175679e-01, -6.2446463427087906e-01, -2.1427274728482519e+00, -3.6091242180602356e-01, -9.3784662004315877e-01, -3.0408455811115820e-01, 2.6996542030296267e-01, 8.4593708219392538e-01, 5.7637800117765847e-01, 1.8263715168532315e+00};
static const casadi_real casadi_c2[28] = {1.6504902577932683e+00, 2.4331475211479581e-01, -5.5560325477657657e-01, -8.8862368618983023e-01, -7.8661078177619226e-01, -1.2384184595363812e-01, 7.6466014319453102e-02, -1.1490563409163945e-01, 3.5055485714667312e-01, 8.5428319433760436e-01, 8.5540178780971698e-01, 3.5546693592787704e-01, -1.1014002235391185e-01, 5.4225420252474121e-02, -5.9360421543474318e-02, -7.2049878276941959e-01, -8.9423324190197540e-01, -6.5747390040005493e-01, -5.6119040751279270e-02, 5.2595229746422900e-01, 2.0185998412225890e+00, -1.4663059367630948e-01, -3.0091808832079570e-01, -8.5787679673409545e-01, -8.5461945690309926e-01, -4.0895728041396195e-01, 2.4315189864354703e-01, 1.8267147476957568e+00};
static const casadi_real casadi_c3[33] = {-3.1575566204037195e-19, -3.1575566204037195e-19, -3.1575566204037195e-19, -3.1575566204037195e-19, 1.9578137815313748e+00, 2.9006954090075547e+00, 3.8438073827983117e+00, 4.7878346935554790e+00, 5.8306947588018776e+00, 7.4276392571227570e+00, 8.8259597484552081e+00, 9.7916952535770569e+00, 1.0737202029436570e+01, 1.1682627353612254e+01, 1.2645737803590833e+01, 1.4031897389910025e+01, 1.5582186662379527e+01, 1.6532358689061844e+01, 1.7476565676817419e+01, 1.8420103153025508e+01, 1.9363418315155638e+01, 2.0306679778305945e+01, 2.1249931149406503e+01, 2.2193181107272292e+01, 2.3136430489846823e+01, 2.4079676681948211e+01, 2.5022907507404678e+01, 2.5966082011033240e+01, 2.6909121414425766e+01, 2.8641039465463830e+01, 2.8641039465463830e+01, 2.8641039465463830e+01, 2.8641039465463830e+01};
static const casadi_real casadi_c4[29] = {4.4415373358260633e-17, 1.0771175243303106e+00, 1.3123781857980437e+00, 6.0050088825905157e-01, -2.3777365002000336e-01, -1.0060300097351524e+00, -1.1539727947030944e+00, -1.0510463519458595e+00, -1.2027601097756726e+00, -8.1603234148686710e-01, -2.5646325220951677e-03, 8.1121973406683412e-01, 1.2016048222679312e+00, 1.0584389724552536e+00, 1.1286901894141566e+00, 1.0605312022180697e+00, 3.7895940984750581e-01, -4.6491646597237662e-01, -1.0851585182666628e+00, -1.1380942624826680e+00, -6.4198751521848618e-01, 1.2620572637868226e+00, 1.1237481746569977e+00, 8.3990955505742293e-01, 3.0745427434368314e-02, -7.7528741276806601e-01, -1.2685078813503041e+00, -1.0517008867384683e+00, 2.8725284721066655e-03};
static const casadi_real casadi_c5[29] = {-1.8844153968447780e-17, 9.8991422231948800e-01, 1.7623977308091385e+00, 2.6971299582069692e+00, 2.8255506786811080e+00, 2.3452085435397314e+00, 1.3211248043551671e+00, -2.1639766079082082e-01, -1.7161036817469812e+00, -2.5316412845192224e+00, -2.8571622064441633e+00, -2.5353949713405939e+00, -1.7265912723924213e+00, -2.4905008428072856e-01, 1.2178764085216540e+00, 2.2412625672972686e+00, 2.7888073398631219e+00, 2.7538502255649497e+00, 2.1768291905378145e+00, 1.2822961423415080e+00, 6.9326721332401875e-01, -1.3278609836528248e+00, -1.6682910880676260e+00, -2.5529075347379773e+00, -2.8397253122141564e+00, -2.5851079000717205e+00, -1.5648705695406695e+00, -1.0509416926006758e+00, 3.4335733792849833e-03};

/* jac_traj:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* jac_traj:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c2,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* traj:(x)->(f) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c3,casadi_s4,casadi_s5,casadi_s2,casadi_c4,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* traj:(x)->(f) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c3,casadi_s4,casadi_s5,casadi_s2,casadi_c5,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* f1tenth_bicycle_model_cost_ext_cost_0_fun:(i0[9],i1[3],i2[],i3[])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+4, *cs;
  casadi_real w0, w1, w3, w4, *w5=w+16, *w6=w+18, *w7=w+20, w8;
  /* #0: @0 = 50 */
  w0 = 50.;
  /* #1: @1 = input[0][6] */
  w1 = arg[0] ? arg[0][6] : 0;
  /* #2: @2 = 00 */
  /* #3: @3 = jac_traj(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w3);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: @2 = 00 */
  /* #5: @4 = jac_traj(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #6: @4 = (-@4) */
  w4 = (- w4 );
  /* #7: @5 = horzcat(@3, @4) */
  rr=w5;
  *rr++ = w3;
  *rr++ = w4;
  /* #8: @5 = @5' */
  /* #9: @3 = traj(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w3);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #10: @4 = traj(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w4);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #11: @6 = horzcat(@3, @4) */
  rr=w6;
  *rr++ = w3;
  *rr++ = w4;
  /* #12: @6 = @6' */
  /* #13: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #14: @4 = input[0][1] */
  w4 = arg[0] ? arg[0][1] : 0;
  /* #15: @7 = vertcat(@3, @4) */
  rr=w7;
  *rr++ = w3;
  *rr++ = w4;
  /* #16: @6 = (@6-@7) */
  for (i=0, rr=w6, cs=w7; i<2; ++i) (*rr++) -= (*cs++);
  /* #17: @3 = dot(@5, @6) */
  w3 = casadi_dot(2, w5, w6);
  /* #18: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #19: @0 = (@0*@3) */
  w0 *= w3;
  /* #20: @3 = 80 */
  w3 = 80.;
  /* #21: @2 = 00 */
  /* #22: @4 = jac_traj(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #23: @2 = 00 */
  /* #24: @8 = jac_traj(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w8);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #25: @5 = horzcat(@4, @8) */
  rr=w5;
  *rr++ = w4;
  *rr++ = w8;
  /* #26: @5 = @5' */
  /* #27: @4 = traj(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w4);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #28: @8 = traj(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w8);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #29: @6 = horzcat(@4, @8) */
  rr=w6;
  *rr++ = w4;
  *rr++ = w8;
  /* #30: @6 = @6' */
  /* #31: @6 = (@6-@7) */
  for (i=0, rr=w6, cs=w7; i<2; ++i) (*rr++) -= (*cs++);
  /* #32: @4 = dot(@5, @6) */
  w4 = casadi_dot(2, w5, w6);
  /* #33: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #34: @3 = (@3*@4) */
  w3 *= w4;
  /* #35: @0 = (@0+@3) */
  w0 += w3;
  /* #36: @3 = 1.3 */
  w3 = 1.3000000000000000e+00;
  /* #37: @4 = input[1][0] */
  w4 = arg[1] ? arg[1][0] : 0;
  /* #38: @3 = (@3*@4) */
  w3 *= w4;
  /* #39: @0 = (@0-@3) */
  w0 -= w3;
  /* #40: @3 = 0.05 */
  w3 = 5.0000000000000003e-02;
  /* #41: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #42: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #43: @3 = (@3*@4) */
  w3 *= w4;
  /* #44: @0 = (@0+@3) */
  w0 += w3;
  /* #45: @3 = 0.5 */
  w3 = 5.0000000000000000e-01;
  /* #46: @4 = input[1][2] */
  w4 = arg[1] ? arg[1][2] : 0;
  /* #47: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #48: @3 = (@3*@4) */
  w3 *= w4;
  /* #49: @0 = (@0+@3) */
  w0 += w3;
  /* #50: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_cost_ext_cost_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_cost_ext_cost_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_cost_ext_cost_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_cost_ext_cost_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_cost_ext_cost_0_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_cost_ext_cost_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_bicycle_model_cost_ext_cost_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_cost_ext_cost_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_cost_ext_cost_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_cost_ext_cost_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_cost_ext_cost_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 23;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 8*sizeof(casadi_int);
  if (sz_w) *sz_w = 23*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
