/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_bicycle_model_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_c8 CASADI_PREFIX(c8)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[2] = {0, 31};
static const casadi_int casadi_s1[1] = {2};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[2] = {0, 33};
static const casadi_int casadi_s5[1] = {3};
static const casadi_int casadi_s6[2] = {0, 29};
static const casadi_int casadi_s7[10] = {12, 1, 0, 6, 0, 1, 2, 3, 4, 9};
static const casadi_int casadi_s8[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s9[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s10[3] = {0, 0, 0};
static const casadi_int casadi_s11[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s12[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

static const casadi_real casadi_c0[31] = {-3.1575566204037195e-19, -3.1575566204037195e-19, -3.1575566204037195e-19, 1.9578137815313748e+00, 2.9006954090075547e+00, 3.8438073827983117e+00, 4.7878346935554790e+00, 5.8306947588018776e+00, 7.4276392571227570e+00, 8.8259597484552081e+00, 9.7916952535770569e+00, 1.0737202029436570e+01, 1.1682627353612254e+01, 1.2645737803590833e+01, 1.4031897389910025e+01, 1.5582186662379527e+01, 1.6532358689061844e+01, 1.7476565676817419e+01, 1.8420103153025508e+01, 1.9363418315155638e+01, 2.0306679778305945e+01, 2.1249931149406503e+01, 2.2193181107272292e+01, 2.3136430489846823e+01, 2.4079676681948211e+01, 2.5022907507404678e+01, 2.5966082011033240e+01, 2.6909121414425766e+01, 2.8641039465463830e+01, 2.8641039465463830e+01, 2.8641039465463830e+01};
static const casadi_real casadi_c1[28] = {1.5168667699517229e+00, 7.9892929063580831e-01, 7.2953621316789885e-01, 1.3613403342198893e-01, -4.9181799495118872e-01, -8.5725316512868344e-01, -1.1422547179021179e+00, -1.1358539512436603e+00, -7.3925559858960566e-01, -3.4185383137046355e-01, 3.3822260474219235e-01, 7.3645992462739795e-01, 1.1366985890865493e+00, 1.1322893608836835e+00, 8.9127841075322145e-01, 5.7881700293571914e-01, -3.7043141701404103e-02, -6.1165841482183891e-01, -9.4832588695175679e-01, -6.2446463427087906e-01, -2.1427274728482519e+00, -3.6091242180602356e-01, -9.3784662004315877e-01, -3.0408455811115820e-01, 2.6996542030296267e-01, 8.4593708219392538e-01, 5.7637800117765847e-01, 1.8263715168532315e+00};
static const casadi_real casadi_c2[28] = {1.6504902577932683e+00, 2.4331475211479581e-01, -5.5560325477657657e-01, -8.8862368618983023e-01, -7.8661078177619226e-01, -1.2384184595363812e-01, 7.6466014319453102e-02, -1.1490563409163945e-01, 3.5055485714667312e-01, 8.5428319433760436e-01, 8.5540178780971698e-01, 3.5546693592787704e-01, -1.1014002235391185e-01, 5.4225420252474121e-02, -5.9360421543474318e-02, -7.2049878276941959e-01, -8.9423324190197540e-01, -6.5747390040005493e-01, -5.6119040751279270e-02, 5.2595229746422900e-01, 2.0185998412225890e+00, -1.4663059367630948e-01, -3.0091808832079570e-01, -8.5787679673409545e-01, -8.5461945690309926e-01, -4.0895728041396195e-01, 2.4315189864354703e-01, 1.8267147476957568e+00};
static const casadi_real casadi_c3[33] = {-3.1575566204037195e-19, -3.1575566204037195e-19, -3.1575566204037195e-19, -3.1575566204037195e-19, 1.9578137815313748e+00, 2.9006954090075547e+00, 3.8438073827983117e+00, 4.7878346935554790e+00, 5.8306947588018776e+00, 7.4276392571227570e+00, 8.8259597484552081e+00, 9.7916952535770569e+00, 1.0737202029436570e+01, 1.1682627353612254e+01, 1.2645737803590833e+01, 1.4031897389910025e+01, 1.5582186662379527e+01, 1.6532358689061844e+01, 1.7476565676817419e+01, 1.8420103153025508e+01, 1.9363418315155638e+01, 2.0306679778305945e+01, 2.1249931149406503e+01, 2.2193181107272292e+01, 2.3136430489846823e+01, 2.4079676681948211e+01, 2.5022907507404678e+01, 2.5966082011033240e+01, 2.6909121414425766e+01, 2.8641039465463830e+01, 2.8641039465463830e+01, 2.8641039465463830e+01, 2.8641039465463830e+01};
static const casadi_real casadi_c4[29] = {4.4415373358260633e-17, 1.0771175243303106e+00, 1.3123781857980437e+00, 6.0050088825905157e-01, -2.3777365002000336e-01, -1.0060300097351524e+00, -1.1539727947030944e+00, -1.0510463519458595e+00, -1.2027601097756726e+00, -8.1603234148686710e-01, -2.5646325220951677e-03, 8.1121973406683412e-01, 1.2016048222679312e+00, 1.0584389724552536e+00, 1.1286901894141566e+00, 1.0605312022180697e+00, 3.7895940984750581e-01, -4.6491646597237662e-01, -1.0851585182666628e+00, -1.1380942624826680e+00, -6.4198751521848618e-01, 1.2620572637868226e+00, 1.1237481746569977e+00, 8.3990955505742293e-01, 3.0745427434368314e-02, -7.7528741276806601e-01, -1.2685078813503041e+00, -1.0517008867384683e+00, 2.8725284721066655e-03};
static const casadi_real casadi_c5[29] = {-1.8844153968447780e-17, 9.8991422231948800e-01, 1.7623977308091385e+00, 2.6971299582069692e+00, 2.8255506786811080e+00, 2.3452085435397314e+00, 1.3211248043551671e+00, -2.1639766079082082e-01, -1.7161036817469812e+00, -2.5316412845192224e+00, -2.8571622064441633e+00, -2.5353949713405939e+00, -1.7265912723924213e+00, -2.4905008428072856e-01, 1.2178764085216540e+00, 2.2412625672972686e+00, 2.7888073398631219e+00, 2.7538502255649497e+00, 2.1768291905378145e+00, 1.2822961423415080e+00, 6.9326721332401875e-01, -1.3278609836528248e+00, -1.6682910880676260e+00, -2.5529075347379773e+00, -2.8397253122141564e+00, -2.5851079000717205e+00, -1.5648705695406695e+00, -1.0509416926006758e+00, 3.4335733792849833e-03};
static const casadi_real casadi_c6[29] = {-3.1575566204037195e-19, -3.1575566204037195e-19, 1.9578137815313748e+00, 2.9006954090075547e+00, 3.8438073827983117e+00, 4.7878346935554790e+00, 5.8306947588018776e+00, 7.4276392571227570e+00, 8.8259597484552081e+00, 9.7916952535770569e+00, 1.0737202029436570e+01, 1.1682627353612254e+01, 1.2645737803590833e+01, 1.4031897389910025e+01, 1.5582186662379527e+01, 1.6532358689061844e+01, 1.7476565676817419e+01, 1.8420103153025508e+01, 1.9363418315155638e+01, 2.0306679778305945e+01, 2.1249931149406503e+01, 2.2193181107272292e+01, 2.3136430489846823e+01, 2.4079676681948211e+01, 2.5022907507404678e+01, 2.5966082011033240e+01, 2.6909121414425766e+01, 2.8641039465463830e+01, 2.8641039465463830e+01};
static const casadi_real casadi_c7[27] = {-7.3340732003056364e-01, -4.7845821558804569e-02, -6.2927273915169746e-01, -6.6550681607331108e-01, -3.6784688915033792e-01, -2.1592625204670457e-01, 4.2739234629110001e-03, 3.3552365362655345e-01, 4.1585702783331990e-01, 7.1930286243487762e-01, 4.1732235285102592e-01, 3.4073449052275817e-01, -3.0031023286301028e-03, -1.9277318966081602e-01, -3.2988267441319519e-01, -6.5248253287843050e-01, -6.0907276111027686e-01, -3.5690834670430915e-01, 3.4334381065526443e-01, -1.6096069642413249e+00, 1.8890174121410954e+00, -6.1164648990628723e-01, 6.7190011437556696e-01, 6.0861785064247531e-01, 6.1071722538680606e-01, -2.0154270533895069e-01, 1.4434788238697100e+00};
static const casadi_real casadi_c8[27] = {-1.4374967823321780e+00, -5.5084584504149270e-01, -3.5315117844466015e-01, 1.0811380511118529e-01, 6.6714293303896322e-01, 1.5175961359988471e-01, -1.2778278320759978e-01, 3.9378127416307207e-01, 5.2712138299104883e-01, 1.1831133144249995e-03, -5.2389361378712218e-01, -3.9638436713349634e-01, 1.1194844556168290e-01, -9.0851909473246270e-02, -6.9800008993672380e-01, -1.8406565342829151e-01, 2.5095689688881917e-01, 6.3750907499915099e-01, 6.1708706948357339e-01, 1.5824505616184352e+00, -2.2955008660575738e+00, -1.6357048138953753e-01, -5.9047494692971403e-01, 3.4534887924390079e-03, 4.7254680376413416e-01, 4.8756601939773392e-01, 1.8286810373078162e+00};

/* jac_traj:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* jac_traj:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c2,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* traj:(x)->(f) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c3,casadi_s4,casadi_s5,casadi_s2,casadi_c4,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* traj:(x)->(f) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c3,casadi_s4,casadi_s5,casadi_s2,casadi_c5,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* jac_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz])->(jac_jac_f_x_x,jac_jac_f_x_out_f[1x1,0nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = zeros(2x1,1nz) */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c6,casadi_s6,casadi_s2,casadi_s2,casadi_c7,1,(&w1),casadi_s3, iw, w);
  /* #3: @1 = ones(2x1,1nz) */
  w1 = 1.;
  /* #4: {@3, NULL} = vertsplit(@1) */
  w3 = w1;
  /* #5: @2 = (@2*@3) */
  w2 *= w3;
  /* #6: (@0[0] = @2) */
  for (rr=(&w0)+0, ss=(&w2); rr!=(&w0)+1; rr+=1) *rr = *ss++;
  /* #7: @0 = @0' */
  /* #8: {@2, NULL} = horzsplit(@0) */
  w2 = w0;
  /* #9: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* jac_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz])->(jac_jac_f_x_x,jac_jac_f_x_out_f[1x1,0nz]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = zeros(2x1,1nz) */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c6,casadi_s6,casadi_s2,casadi_s2,casadi_c8,1,(&w1),casadi_s3, iw, w);
  /* #3: @1 = ones(2x1,1nz) */
  w1 = 1.;
  /* #4: {@3, NULL} = vertsplit(@1) */
  w3 = w1;
  /* #5: @2 = (@2*@3) */
  w2 *= w3;
  /* #6: (@0[0] = @2) */
  for (rr=(&w0)+0, ss=(&w2); rr!=(&w0)+1; rr+=1) *rr = *ss++;
  /* #7: @0 = @0' */
  /* #8: {@2, NULL} = horzsplit(@0) */
  w2 = w0;
  /* #9: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* jac_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz])->(jac_jac_f_x_x,jac_jac_f_x_out_f[1x1,0nz]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = zeros(2x1,1nz) */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c6,casadi_s6,casadi_s2,casadi_s2,casadi_c8,1,(&w1),casadi_s3, iw, w);
  /* #3: @1 = ones(2x1,1nz) */
  w1 = 1.;
  /* #4: {@3, NULL} = vertsplit(@1) */
  w3 = w1;
  /* #5: @2 = (@2*@3) */
  w2 *= w3;
  /* #6: (@0[0] = @2) */
  for (rr=(&w0)+0, ss=(&w2); rr!=(&w0)+1; rr+=1) *rr = *ss++;
  /* #7: @0 = @0' */
  /* #8: {@2, NULL} = horzsplit(@0) */
  w2 = w0;
  /* #9: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* jac_jac_traj:(x,out_f[1x1,0nz],out_jac_f_x[1x1,0nz])->(jac_jac_f_x_x,jac_jac_f_x_out_f[1x1,0nz]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = zeros(2x1,1nz) */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = BSpline(@1) */
  casadi_clear((&w2), 1);
  CASADI_PREFIX(nd_boor_eval)((&w2),1,casadi_c6,casadi_s6,casadi_s2,casadi_s2,casadi_c7,1,(&w1),casadi_s3, iw, w);
  /* #3: @1 = ones(2x1,1nz) */
  w1 = 1.;
  /* #4: {@3, NULL} = vertsplit(@1) */
  w3 = w1;
  /* #5: @2 = (@2*@3) */
  w2 *= w3;
  /* #6: (@0[0] = @2) */
  for (rr=(&w0)+0, ss=(&w2); rr!=(&w0)+1; rr+=1) *rr = *ss++;
  /* #7: @0 = @0' */
  /* #8: {@2, NULL} = horzsplit(@0) */
  w2 = w0;
  /* #9: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* f1tenth_bicycle_model_cost_ext_cost_fun_jac:(i0[9],i1[3],i2[],i3[])->(o0,o1[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+2, *rr;
  const casadi_real **arg1=arg+4, *cs;
  casadi_real w0, w1, w3, w5, *w6=w+16, *w7=w+18, *w8=w+20, w10, w12, *w13=w+24, *w14=w+26, w15, w16, w22, w23, w24, *w25=w+33, *w26=w+39;
  /* #0: @0 = 50 */
  w0 = 50.;
  /* #1: @1 = input[0][6] */
  w1 = arg[0] ? arg[0][6] : 0;
  /* #2: @2 = 00 */
  /* #3: @3 = jac_traj(@1, @2) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w3);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: @4 = 00 */
  /* #5: @5 = jac_traj(@1, @4) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w5);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #6: @5 = (-@5) */
  w5 = (- w5 );
  /* #7: @6 = horzcat(@3, @5) */
  rr=w6;
  *rr++ = w3;
  *rr++ = w5;
  /* #8: @6 = @6' */
  /* #9: @3 = traj(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w3);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #10: @5 = traj(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w5);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #11: @7 = horzcat(@3, @5) */
  rr=w7;
  *rr++ = w3;
  *rr++ = w5;
  /* #12: @7 = @7' */
  /* #13: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #14: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #15: @8 = vertcat(@3, @5) */
  rr=w8;
  *rr++ = w3;
  *rr++ = w5;
  /* #16: @7 = (@7-@8) */
  for (i=0, rr=w7, cs=w8; i<2; ++i) (*rr++) -= (*cs++);
  /* #17: @3 = dot(@6, @7) */
  w3 = casadi_dot(2, w6, w7);
  /* #18: @5 = sq(@3) */
  w5 = casadi_sq( w3 );
  /* #19: @0 = (@0*@5) */
  w0 *= w5;
  /* #20: @5 = 80 */
  w5 = 80.;
  /* #21: @9 = 00 */
  /* #22: @10 = jac_traj(@1, @9) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w10);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #23: @11 = 00 */
  /* #24: @12 = jac_traj(@1, @11) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w12);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #25: @13 = horzcat(@10, @12) */
  rr=w13;
  *rr++ = w10;
  *rr++ = w12;
  /* #26: @13 = @13' */
  /* #27: @10 = traj(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w10);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #28: @12 = traj(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w12);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #29: @14 = horzcat(@10, @12) */
  rr=w14;
  *rr++ = w10;
  *rr++ = w12;
  /* #30: @14 = @14' */
  /* #31: @14 = (@14-@8) */
  for (i=0, rr=w14, cs=w8; i<2; ++i) (*rr++) -= (*cs++);
  /* #32: @10 = dot(@13, @14) */
  w10 = casadi_dot(2, w13, w14);
  /* #33: @12 = sq(@10) */
  w12 = casadi_sq( w10 );
  /* #34: @5 = (@5*@12) */
  w5 *= w12;
  /* #35: @0 = (@0+@5) */
  w0 += w5;
  /* #36: @5 = 1.3 */
  w5 = 1.3000000000000000e+00;
  /* #37: @12 = input[1][0] */
  w12 = arg[1] ? arg[1][0] : 0;
  /* #38: @5 = (@5*@12) */
  w5 *= w12;
  /* #39: @0 = (@0-@5) */
  w0 -= w5;
  /* #40: @5 = 0.05 */
  w5 = 5.0000000000000003e-02;
  /* #41: @12 = input[1][1] */
  w12 = arg[1] ? arg[1][1] : 0;
  /* #42: @15 = sq(@12) */
  w15 = casadi_sq( w12 );
  /* #43: @5 = (@5*@15) */
  w5 *= w15;
  /* #44: @0 = (@0+@5) */
  w0 += w5;
  /* #45: @5 = 0.5 */
  w5 = 5.0000000000000000e-01;
  /* #46: @15 = input[1][2] */
  w15 = arg[1] ? arg[1][2] : 0;
  /* #47: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #48: @5 = (@5*@16) */
  w5 *= w16;
  /* #49: @0 = (@0+@5) */
  w0 += w5;
  /* #50: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #51: @0 = -1.3 */
  w0 = -1.3000000000000000e+00;
  /* #52: @5 = 0.05 */
  w5 = 5.0000000000000003e-02;
  /* #53: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #54: @5 = (@5*@12) */
  w5 *= w12;
  /* #55: @12 = 0.5 */
  w12 = 5.0000000000000000e-01;
  /* #56: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #57: @12 = (@12*@15) */
  w12 *= w15;
  /* #58: @15 = 50 */
  w15 = 50.;
  /* #59: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #60: @15 = (@15*@3) */
  w15 *= w3;
  /* #61: @6 = (@15*@6) */
  for (i=0, rr=w6, cs=w6; i<2; ++i) (*rr++)  = (w15*(*cs++));
  /* #62: @8 = (-@6) */
  for (i=0, rr=w8, cs=w6; i<2; ++i) *rr++ = (- *cs++ );
  /* #63: @3 = 80 */
  w3 = 80.;
  /* #64: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #65: @3 = (@3*@10) */
  w3 *= w10;
  /* #66: @13 = (@3*@13) */
  for (i=0, rr=w13, cs=w13; i<2; ++i) (*rr++)  = (w3*(*cs++));
  /* #67: @8 = (@8-@13) */
  for (i=0, rr=w8, cs=w13; i<2; ++i) (*rr++) -= (*cs++);
  /* #68: {@10, @16} = vertsplit(@8) */
  w10 = w8[0];
  w16 = w8[1];
  /* #69: @17 = 00 */
  /* #70: @18 = 00 */
  /* #71: @19 = 00 */
  /* #72: @20 = 00 */
  /* #73: @21 = 00 */
  /* #74: @22 = jac_traj(@1, @21) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w22);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #75: @13 = @13' */
  /* #76: {@23, @24} = horzsplit(@13) */
  w23 = w13[0];
  w24 = w13[1];
  /* #77: @22 = (@22*@24) */
  w22 *= w24;
  /* #78: @21 = 00 */
  /* #79: @24 = jac_traj(@1, @21) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w24);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #80: @24 = (@24*@23) */
  w24 *= w23;
  /* #81: @22 = (@22+@24) */
  w22 += w24;
  /* #82: @21 = 00 */
  /* #83: {@24, NULL} = jac_jac_traj(@1, @11, @21) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  res1[0]=(&w24);
  res1[1]=0;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #84: @14 = (@3*@14) */
  for (i=0, rr=w14, cs=w14; i<2; ++i) (*rr++)  = (w3*(*cs++));
  /* #85: @14 = @14' */
  /* #86: {@3, @23} = horzsplit(@14) */
  w3 = w14[0];
  w23 = w14[1];
  /* #87: @24 = (@24*@23) */
  w24 *= w23;
  /* #88: @22 = (@22+@24) */
  w22 += w24;
  /* #89: @11 = 00 */
  /* #90: {@24, NULL} = jac_jac_traj(@1, @9, @11) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  res1[0]=(&w24);
  res1[1]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #91: @24 = (@24*@3) */
  w24 *= w3;
  /* #92: @22 = (@22+@24) */
  w22 += w24;
  /* #93: @9 = 00 */
  /* #94: @24 = jac_traj(@1, @9) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w24);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #95: @6 = @6' */
  /* #96: {@3, @23} = horzsplit(@6) */
  w3 = w6[0];
  w23 = w6[1];
  /* #97: @24 = (@24*@23) */
  w24 *= w23;
  /* #98: @22 = (@22+@24) */
  w22 += w24;
  /* #99: @9 = 00 */
  /* #100: @24 = jac_traj(@1, @9) */
  arg1[0]=(&w1);
  arg1[1]=0;
  res1[0]=(&w24);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #101: @24 = (@24*@3) */
  w24 *= w3;
  /* #102: @22 = (@22+@24) */
  w22 += w24;
  /* #103: @9 = 00 */
  /* #104: {@24, NULL} = jac_jac_traj(@1, @4, @9) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  res1[0]=(&w24);
  res1[1]=0;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #105: @7 = (@15*@7) */
  for (i=0, rr=w7, cs=w7; i<2; ++i) (*rr++)  = (w15*(*cs++));
  /* #106: @7 = @7' */
  /* #107: {@15, @3} = horzsplit(@7) */
  w15 = w7[0];
  w3 = w7[1];
  /* #108: @24 = (@24*@3) */
  w24 *= w3;
  /* #109: @22 = (@22-@24) */
  w22 -= w24;
  /* #110: @4 = 00 */
  /* #111: {@24, NULL} = jac_jac_traj(@1, @2, @4) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=0;
  res1[0]=(&w24);
  res1[1]=0;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #112: @24 = (@24*@15) */
  w24 *= w15;
  /* #113: @22 = (@22+@24) */
  w22 += w24;
  /* #114: @2 = 00 */
  /* #115: @4 = 00 */
  /* #116: @25 = vertcat(@0, @5, @12, @10, @16, @17, @18, @19, @20, @22, @2, @4) */
  rr=w25;
  *rr++ = w0;
  *rr++ = w5;
  *rr++ = w12;
  *rr++ = w10;
  *rr++ = w16;
  *rr++ = w22;
  /* #117: @26 = dense(@25) */
  casadi_densify(w25, casadi_s7, w26, 0);
  /* #118: output[1][0] = @26 */
  casadi_copy(w26, 12, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_bicycle_model_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s9;
    case 2: return casadi_s10;
    case 3: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    case 1: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 51;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 8*sizeof(casadi_int);
  if (sz_w) *sz_w = 51*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
